FROM eclipse-temurin:17-jre
EXPOSE 7002
ADD target/recommendation-service-0.0.1-SNAPSHOT.jar recommendation-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/recommendation-service-0.0.1-SNAPSHOT.jar"]