FROM eclipse-temurin:17-jre
EXPOSE 7000
ADD target/product-composite-service-0.0.1-SNAPSHOT.jar product-composite-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/product-composite-service-0.0.1-SNAPSHOT.jar"]